Repository SYSTEM-GPM/reserva-api, pull requests merged in 2023-06, with the labels that each got.

#12 feature/cadastrar-passageiros
  src/main/java/reserva_api/dtos/PassageirosDto.java
  src/main/java/reserva_api/dtos/SolicitacaoTransporteDto.java
  src/main/java/reserva_api/repositories/PassageirosRepository.java
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/RecursoService.java
  src/main/java/reserva_api/services/ViagemService.java
Labels: feature, refactor

#13 refactor/visualizar-motorista
  src/main/java/reserva_api/dtos/projection/MotoristaProjection.java
  src/main/java/reserva_api/repositories/MotoristaRepository.java
  src/main/java/reserva_api/resources/MotoristaResource.java
  src/main/java/reserva_api/services/MotoristaService.java
Labels: refactor

#15 feature/listagem-solicitacao-local-transporte
  src/main/java/reserva_api/dtos/projection/SolicitacaoLocalProjection.java
  src/main/java/reserva_api/models/enums/StatusSolicitacao.java
  src/main/java/reserva_api/repositories/SolicitacaoRepository.java
  src/main/java/reserva_api/repositories/ViagemRepository.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/SolicitacaoService.java
  src/main/java/reserva_api/services/ViagemService.java
Labels: feature

#16 listagem-solicitacao-transporte-pessoa
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/ViagemService.java
Labels: feature

#17 Feature/soft delete
  src/main/java/reserva_api/models/Recurso.java
  src/main/java/reserva_api/models/SetorModel.java
  src/main/java/reserva_api/repositories/PessoaRepository.java
  src/main/java/reserva_api/repositories/SolicitacaoRepository.java
  src/main/java/reserva_api/repositories/filters/RecursoFilter.java
  src/main/java/reserva_api/resources/RecursoResource.java
  src/main/java/reserva_api/resources/SetorResource.java
  src/main/java/reserva_api/resources/exceptions/ResourceExceptionHandler.java
  src/main/java/reserva_api/services/PessoaService.java
  src/main/java/reserva_api/services/SolicitacaoService.java
  src/main/java/reserva_api/utils/MensagemEmailUtil.java
Labels: feature

#18 Bugfix/soft delete motorista
  src/main/java/reserva_api/models/MotoristaModel.java
  src/main/java/reserva_api/repositories/MotoristaRepository.java
  src/main/java/reserva_api/repositories/ViagemRepository.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/MotoristaService.java
  src/main/java/reserva_api/services/ViagemService.java
Labels: bug

#19 refactor/listagem-motorista-pessoa-st-recentes
  src/main/java/reserva_api/repositories/MotoristaRepository.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/ViagemService.java
Labels: feature, refactor

#20 refactor/listagem-paginacao
  src/main/java/reserva_api/repositories/MotoristaRepository.java
  src/main/java/reserva_api/repositories/SolicitacaoRepository.java
  src/main/java/reserva_api/services/MotoristaService.java
  src/main/java/reserva_api/services/SolicitacaoService.java
Labels: refactor

#21 fix/listagem-motorista-em-pessoa
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/services/PessoaService.java
Labels: refactor

#22 feat: adiciona envio de emails no fluxo de auto cadastro
  src/main/java/reserva_api/cors/CorsFilter.java
  src/main/java/reserva_api/dtos/EnviaEmailsAutoCadastroDto.java
  src/main/java/reserva_api/dtos/EnviaEmailsUpdateStatusDto.java
  src/main/java/reserva_api/resources/ComunicacaoInternaResource.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/security/WebSecurityConfiguracao.java
  src/main/java/reserva_api/utils/Constantes.java
  src/main/java/reserva_api/utils/MensagemEmailUtil.java
Labels: feature, refactor

#23 refactor: altera listagem de viagens e locais
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/SolicitacaoService.java
  src/main/java/reserva_api/services/ViagemService.java
Labels: refactor
