Repository SYSTEM-GPM/reserva-api, pull requests merged in 2023-05, with the labels that each got.

#1 Feature/tipo perfil e email service
  pom.xml
  src/main/java/reserva_api/dto/PessoaDto.java
  src/main/java/reserva_api/model/Motorista.java
  src/main/java/reserva_api/model/Pessoa.java
  src/main/java/reserva_api/model/enums/StatusConta.java
  src/main/java/reserva_api/model/enums/TipoPerfil.java
  src/main/java/reserva_api/model/enums/TipoVinculo.java
  src/main/java/reserva_api/repositories/filters/PessoaFilter.java
  src/main/java/reserva_api/repositories/pessoa/PessoaRepositoryQueryImpl.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/services/EnviaEmailService.java
  src/main/java/reserva_api/utils/MensagemEmailUtil.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Criar_Tabelas_Inicial.sql
  src/main/resources/db/migration/V4__Popular_Tabela_Pessoa.sql
Labels: feature

#5 Feature/cadastrar e atualizar - local, transporte e setor
  src/main/java/reserva_api/ReservaApiApplication.java
  src/main/java/reserva_api/dtos/LocalDto.java
  src/main/java/reserva_api/dtos/SetorDto.java
  src/main/java/reserva_api/dtos/TransporteDto.java
  src/main/java/reserva_api/models/LocalModel.java
  src/main/java/reserva_api/models/SetorModel.java
  src/main/java/reserva_api/models/TransporteModel.java
  src/main/java/reserva_api/models/Viagem.java
  src/main/java/reserva_api/repositories/LocalRepository.java
  src/main/java/reserva_api/repositories/RecursoRepository.java
  src/main/java/reserva_api/repositories/SetorRepository.java
  src/main/java/reserva_api/repositories/TransporteRepository.java
  src/main/java/reserva_api/repositories/solicitacao/SolicitacaoRepositoryQueryImpl.java
  src/main/java/reserva_api/resources/RecursoResource.java
  src/main/java/reserva_api/resources/SetorResource.java
  src/main/java/reserva_api/services/RecursoService.java
  src/main/java/reserva_api/services/SetorService.java
  src/main/resources/db/migration/V1__Criar_Tabelas_Inicial.sql
Labels: feature

#7 refactor: remove mascara para cpf, telefone e siape em cadastro e atu…
  src/main/java/reserva_api/dtos/PessoaDto.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/resources/db/migration/V4__Popular_Tabela_Pessoa.sql
Labels: refactor

#8 Feature/login
  pom.xml
  src/main/java/reserva_api/data/DetalheUsuarioData.java
  src/main/java/reserva_api/models/PessoaModel.java
  src/main/java/reserva_api/resources/LoginResource.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/resources/exceptions/ResourceExceptionHandler.java
  src/main/java/reserva_api/security/JwtAutentificarFilter.java
  src/main/java/reserva_api/security/JwtValidarFilter.java
  src/main/java/reserva_api/security/WebSecurityConfiguracao.java
  src/main/java/reserva_api/services/DetalheUsuarioService.java
  src/main/java/reserva_api/utils/LoginResposta.java
  src/main/java/reserva_api/utils/MensagemEmailUtil.java
  src/main/resources/db/migration/V8__Adicionando_Administrador.sql
Labels: feature

#9 feature/cadastrar-solicitacao-local
  src/main/java/reserva_api/dtos/ReservaDto.java
  src/main/java/reserva_api/dtos/SolicitacaoLocalDto.java
  src/main/java/reserva_api/models/Solicitacao.java
  src/main/java/reserva_api/repositories/filters/RecursoFilter.java
  src/main/java/reserva_api/repositories/solicitacao/SolicitacaoRepositoryQueryImpl.java
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/SolicitacaoService.java
  src/main/resources/db/migration/V1__Criar_Tabelas_Inicial.sql
Labels: feature

#10 Feature/cadastrar-solicitacao-transporte
  src/main/java/reserva_api/ReservaApiApplication.java
  src/main/java/reserva_api/dtos/ReservaDto.java
  src/main/java/reserva_api/dtos/SolicitacaoLocalDto.java
  src/main/java/reserva_api/dtos/SolicitacaoTransporteAtualizarDto.java
  src/main/java/reserva_api/dtos/SolicitacaoTransporteDto.java
  src/main/java/reserva_api/models/MotoristaModel.java
  src/main/java/reserva_api/models/PassageirosModel.java
  src/main/java/reserva_api/models/Solicitacao.java
  src/main/java/reserva_api/models/Viagem.java
  src/main/java/reserva_api/repositories/ViagemRepository.java
  src/main/java/reserva_api/repositories/filters/RecursoFilter.java
  src/main/java/reserva_api/repositories/solicitacao/SolicitacaoRepositoryQueryImpl.java
  src/main/java/reserva_api/resources/SolicitacaoResource.java
  src/main/java/reserva_api/services/SolicitacaoService.java
  src/main/java/reserva_api/services/ViagemService.java
  src/main/resources/db/migration/V1__Criar_Tabelas_Inicial.sql
  src/main/resources/db/migration/V5__Populando_Tabela_Solicitacao.sql
  src/main/resources/db/migration/V6__Populando_Tabelas_Viagem_e_Passageiro.sql
Labels: feature, refactor

#11 Feature/autocadastro
  pom.xml
  src/main/java/reserva_api/dtos/AtualizarStatusDto.java
  src/main/java/reserva_api/dtos/CadastroUsuarioDto.java
  src/main/java/reserva_api/resources/LoginResource.java
  src/main/java/reserva_api/resources/PessoaResource.java
  src/main/java/reserva_api/resources/exceptions/ResourceExceptionHandler.java
  src/main/java/reserva_api/security/WebSecurityConfiguracao.java
  src/main/java/reserva_api/utils/MensagemEmailUtil.java
  src/main/resources/db/migration/V4__Popular_Tabela_Pessoa.sql
Labels: feature
